!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.8 (r4996) - 25 Oct 2013 15:08
!
!  Differentiation of hfun in forward (tangent) mode (with options fixinterface):
!   variations   of useful results: h
!   with respect to varying inputs: p x
!   RW status of diff variables: h:out p:in x:in
! Kepler
SUBROUTINE HFUN_D(x, xd, p, pd, c, h, hd)
  IMPLICIT NONE
  DOUBLE PRECISION, INTENT(IN) :: x(2), p(2), c(2)
  DOUBLE PRECISION, INTENT(IN) :: xd(2), pd(2)
  DOUBLE PRECISION, INTENT(OUT) :: h
  DOUBLE PRECISION, INTENT(OUT) :: hd
! local variables
  DOUBLE PRECISION :: r, th, pr, pth
  DOUBLE PRECISION :: rd, prd, pthd
  DOUBLE PRECISION :: alpha, delta, beta, nu1, nu2, mu1, mu2, m2
  DOUBLE PRECISION :: betad, nu1d, mu1d, mu2d, m2d
  INTRINSIC COS
  INTRINSIC SIN
  INTRINSIC SQRT
  DOUBLE PRECISION :: arg1
  DOUBLE PRECISION :: arg1d
  DOUBLE PRECISION :: result1
  DOUBLE PRECISION :: result1d
  rd = xd(1)
  r = x(1)
  th = x(2)
  prd = pd(1)
  pr = p(1)
  pthd = pd(2)
  pth = p(2)
  alpha = c(1)
  delta = c(2)
  betad = -(delta*rd*SIN(r))
  beta = delta*COS(r)
  nu1d = -(alpha*rd*COS(r))
  nu1 = -(alpha*SIN(r))
  nu2 = 1d0
  mu1d = betad*nu1 + beta*nu1d
  mu1 = beta*nu1
  mu2d = nu2*betad
  mu2 = beta*nu2
  m2d = 2*SIN(r)*rd*COS(r)
  m2 = SIN(r)**2
  arg1d = 2*pr*prd + (2*pth*pthd*m2-pth**2*m2d)/m2**2
  arg1 = pr**2 + pth**2/m2
  IF (arg1 .EQ. 0.0) THEN
    result1d = 0.D0
  ELSE
    result1d = arg1d/(2.0*SQRT(arg1))
  END IF
  result1 = SQRT(arg1)
  hd = mu1d*pr + mu1*prd + mu2d*pth + mu2*pthd + result1d
  h = mu1*pr + mu2*pth + result1
END SUBROUTINE HFUN_D

