!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.8 (r4996) - 25 Oct 2013 15:08
!
!  Differentiation of hfun_d in forward (tangent) mode (with options fixinterface):
!   variations   of useful results: hd
!   with respect to varying inputs: p x
!   RW status of diff variables: p:in x:in hd:out
!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.8 (r4996) - 25 Oct 2013 15:08
!
!  Differentiation of hfun in forward (tangent) mode (with options fixinterface):
!   variations   of useful results: h
!   with respect to varying inputs: p x
!   RW status of diff variables: h:out p:in x:in
! Kepler
SUBROUTINE HFUN_D_D(x, xd0, xd, p, pd0, pd, c, h, hd, hdd)
  IMPLICIT NONE
  DOUBLE PRECISION, INTENT(IN) :: x(2), p(2), c(2)
  DOUBLE PRECISION, INTENT(IN) :: xd0(2), pd0(2)
  DOUBLE PRECISION, INTENT(IN) :: xd(2), pd(2)
  DOUBLE PRECISION, INTENT(OUT) :: h
  DOUBLE PRECISION, INTENT(OUT) :: hd
  DOUBLE PRECISION, INTENT(OUT) :: hdd
! local variables
  DOUBLE PRECISION :: r, th, pr, pth
  DOUBLE PRECISION :: rd0, prd0, pthd0
  DOUBLE PRECISION :: rd, prd, pthd
  DOUBLE PRECISION :: alpha, delta, beta, nu1, nu2, mu1, mu2, m2
  DOUBLE PRECISION :: betad0, nu1d0, mu1d0, mu2d0, m2d0
  DOUBLE PRECISION :: betad, nu1d, mu1d, mu2d, m2d
  DOUBLE PRECISION :: betadd, nu1dd, mu1dd, mu2dd, m2dd
  INTRINSIC COS
  INTRINSIC SIN
  INTRINSIC SQRT
  DOUBLE PRECISION :: arg1
  DOUBLE PRECISION :: arg1d0
  DOUBLE PRECISION :: arg1d
  DOUBLE PRECISION :: arg1dd
  DOUBLE PRECISION :: result1
  DOUBLE PRECISION :: result1d
  DOUBLE PRECISION :: result1dd
  DOUBLE PRECISION :: result10
  DOUBLE PRECISION :: result10d
  rd = xd(1)
  rd0 = xd0(1)
  r = x(1)
  th = x(2)
  prd = pd(1)
  prd0 = pd0(1)
  pr = p(1)
  pthd = pd(2)
  pthd0 = pd0(2)
  pth = p(2)
  alpha = c(1)
  delta = c(2)
  betadd = -(delta*rd*rd0*COS(r))
  betad = -(delta*rd*SIN(r))
  betad0 = -(delta*rd0*SIN(r))
  beta = delta*COS(r)
  nu1dd = alpha*rd*rd0*SIN(r)
  nu1d = -(alpha*rd*COS(r))
  nu1d0 = -(alpha*rd0*COS(r))
  nu1 = -(alpha*SIN(r))
  nu2 = 1d0
  mu1dd = betadd*nu1 + betad*nu1d0 + betad0*nu1d + beta*nu1dd
  mu1d = betad*nu1 + beta*nu1d
  mu1d0 = betad0*nu1 + beta*nu1d0
  mu1 = beta*nu1
  mu2dd = nu2*betadd
  mu2d = nu2*betad
  mu2d0 = nu2*betad0
  mu2 = beta*nu2
  m2dd = 2*rd*(rd0*COS(r)**2-SIN(r)**2*rd0)
  m2d = 2*SIN(r)*rd*COS(r)
  m2d0 = 2*SIN(r)*rd0*COS(r)
  m2 = SIN(r)**2
  arg1dd = 2*prd*prd0 + ((2*pthd*(pthd0*m2+pth*m2d0)-2*pth*pthd0*m2d-pth&
&   **2*m2dd)*m2**2-(2*pth*pthd*m2-pth**2*m2d)*2*m2*m2d0)/(m2**2)**2
  arg1d = 2*pr*prd + (2*pth*pthd*m2-pth**2*m2d)/m2**2
  arg1d0 = 2*pr*prd0 + (2*pth*pthd0*m2-pth**2*m2d0)/m2**2
  arg1 = pr**2 + pth**2/m2
  IF (arg1 .EQ. 0.0) THEN
    result1d = 0.d0
    result1dd = 0.D0
  ELSE
    IF (arg1 .EQ. 0.0) THEN
      result10d = 0.D0
    ELSE
      result10d = arg1d0/(2.0*SQRT(arg1))
    END IF
    result10 = SQRT(arg1)
    result1dd = (arg1dd*2.0*result10-arg1d*2.0*result10d)/(2.0*result10)&
&     **2
    result1d = arg1d/(2.0*result10)
  END IF
  result1 = SQRT(arg1)
  hdd = mu1dd*pr + mu1d*prd0 + prd*mu1d0 + mu2dd*pth + mu2d*pthd0 + pthd&
&   *mu2d0 + result1dd
  hd = mu1d*pr + mu1*prd + mu2d*pth + mu2*pthd + result1d
  h = mu1*pr + mu2*pth + result1
END SUBROUTINE HFUN_D_D

